apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
       labels:
         app: mypod
    spec:
      containers:
        - name: mycontainer
          image: abhishek00007/lampp:100
          volumeMounts:
           - name: task-pv-storage
             mountPath: /app
          ports:
          - containerPort: 80
         
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: mypvc      

      
---
apiVersion: v1
kind: Service
metadata:
  name: phpservice
spec:
  selector:
    app: mypod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual
  volumeName: my-pv   
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

 
